/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CardRouteImport } from './routes/card'
import { Route as CreativeServicesRouteImport } from './routes/creative-services'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyPassesRouteImport } from './routes/my-passes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LiveSportsIndexRouteImport } from './routes/live-sports.index'
import { Route as LiveSportsMatchIdRouteImport } from './routes/live-sports.$matchId'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeServicesRoute = CreativeServicesRouteImport.update({
  id: '/creative-services',
  path: '/creative-services',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPassesRoute = MyPassesRouteImport.update({
  id: '/my-passes',
  path: '/my-passes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSportsIndexRoute = LiveSportsIndexRouteImport.update({
  id: '/live-sports/',
  path: '/live-sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSportsMatchIdRoute = LiveSportsMatchIdRouteImport.update({
  id: '/live-sports/$matchId',
  path: '/live-sports/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/creative-services': typeof CreativeServicesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-passes': typeof MyPassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/live-sports/$matchId': typeof LiveSportsMatchIdRoute
  '/p/$slug': typeof PSlugRoute
  '/live-sports/': typeof LiveSportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/creative-services': typeof CreativeServicesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-passes': typeof MyPassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/live-sports/$matchId': typeof LiveSportsMatchIdRoute
  '/p/$slug': typeof PSlugRoute
  '/live-sports': typeof LiveSportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/creative-services': typeof CreativeServicesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-passes': typeof MyPassesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/live-sports/$matchId': typeof LiveSportsMatchIdRoute
  '/p/$slug': typeof PSlugRoute
  '/live-sports/': typeof LiveSportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/card'
    | '/creative-services'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/my-passes'
    | '/reset-password'
    | '/signup'
    | '/live-sports/$matchId'
    | '/p/$slug'
    | '/live-sports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/card'
    | '/creative-services'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/my-passes'
    | '/reset-password'
    | '/signup'
    | '/live-sports/$matchId'
    | '/p/$slug'
    | '/live-sports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/card'
    | '/creative-services'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/my-passes'
    | '/reset-password'
    | '/signup'
    | '/live-sports/$matchId'
    | '/p/$slug'
    | '/live-sports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardRoute: typeof CardRoute
  CreativeServicesRoute: typeof CreativeServicesRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyPassesRoute: typeof MyPassesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LiveSportsMatchIdRoute: typeof LiveSportsMatchIdRoute
  PSlugRoute: typeof PSlugRoute
  LiveSportsIndexRoute: typeof LiveSportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-services': {
      id: '/creative-services'
      path: '/creative-services'
      fullPath: '/creative-services'
      preLoaderRoute: typeof CreativeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-passes': {
      id: '/my-passes'
      path: '/my-passes'
      fullPath: '/my-passes'
      preLoaderRoute: typeof MyPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-sports/': {
      id: '/live-sports/'
      path: '/live-sports'
      fullPath: '/live-sports/'
      preLoaderRoute: typeof LiveSportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-sports/$matchId': {
      id: '/live-sports/$matchId'
      path: '/live-sports/$matchId'
      fullPath: '/live-sports/$matchId'
      preLoaderRoute: typeof LiveSportsMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardRoute: CardRoute,
  CreativeServicesRoute: CreativeServicesRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyPassesRoute: MyPassesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LiveSportsMatchIdRoute: LiveSportsMatchIdRoute,
  PSlugRoute: PSlugRoute,
  LiveSportsIndexRoute: LiveSportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
