/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBraceletRouteImport } from './routes/account.bracelet'
import { Route as AccountDonateRouteImport } from './routes/account.donate'
import { Route as AccountMinorsRouteImport } from './routes/account.minors'
import { Route as AccountPaymentProofRouteImport } from './routes/account.payment-proof'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountTeamRouteImport } from './routes/account.team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDraftRouteImport } from './routes/admin.draft'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminLeagueRouteImport } from './routes/admin.league'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminMatchmakingRouteImport } from './routes/admin.matchmaking'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminRosterRouteImport } from './routes/admin.roster'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminScoreRouteImport } from './routes/admin.score'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiRegistrationAssistantRouteImport } from './routes/api/registration-assistant'
import { Route as CardPlayerIdRouteImport } from './routes/card.$playerId'
import { Route as ConsentTokenRouteImport } from './routes/consent.$token'
import { Route as DivisionsSlugRouteImport } from './routes/divisions.$slug'
import { Route as LegalCodeOfConductRouteImport } from './routes/legal.code-of-conduct'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundPolicyRouteImport } from './routes/legal.refund-policy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalWaiverRouteImport } from './routes/legal.waiver'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as TUidRouteImport } from './routes/t.$uid'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBraceletRoute = AccountBraceletRouteImport.update({
  id: '/account/bracelet',
  path: '/account/bracelet',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDonateRoute = AccountDonateRouteImport.update({
  id: '/account/donate',
  path: '/account/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMinorsRoute = AccountMinorsRouteImport.update({
  id: '/account/minors',
  path: '/account/minors',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentProofRoute = AccountPaymentProofRouteImport.update({
  id: '/account/payment-proof',
  path: '/account/payment-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTeamRoute = AccountTeamRouteImport.update({
  id: '/account/team',
  path: '/account/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/admin/donations',
  path: '/admin/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDraftRoute = AdminDraftRouteImport.update({
  id: '/admin/draft',
  path: '/admin/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeagueRoute = AdminLeagueRouteImport.update({
  id: '/admin/league',
  path: '/admin/league',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/admin/ledger',
  path: '/admin/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchmakingRoute = AdminMatchmakingRouteImport.update({
  id: '/admin/matchmaking',
  path: '/admin/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/admin/players',
  path: '/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRosterRoute = AdminRosterRouteImport.update({
  id: '/admin/roster',
  path: '/admin/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScoreRoute = AdminScoreRouteImport.update({
  id: '/admin/score',
  path: '/admin/score',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationAssistantRoute =
  ApiRegistrationAssistantRouteImport.update({
    id: '/api/registration-assistant',
    path: '/api/registration-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const CardPlayerIdRoute = CardPlayerIdRouteImport.update({
  id: '/card/$playerId',
  path: '/card/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentTokenRoute = ConsentTokenRouteImport.update({
  id: '/consent/$token',
  path: '/consent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsSlugRoute = DivisionsSlugRouteImport.update({
  id: '/divisions/$slug',
  path: '/divisions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCodeOfConductRoute = LegalCodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundPolicyRoute = LegalRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalWaiverRoute = LegalWaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => LegalRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TUidRoute = TUidRouteImport.update({
  id: '/t/$uid',
  path: '/t/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/leaders': typeof LeadersRoute
  '/legal': typeof LegalRouteWithChildren
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/bracelet': typeof AccountBraceletRoute
  '/account/donate': typeof AccountDonateRoute
  '/account/minors': typeof AccountMinorsRoute
  '/account/payment-proof': typeof AccountPaymentProofRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/team': typeof AccountTeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/draft': typeof AdminDraftRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/league': typeof AdminLeagueRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/matchmaking': typeof AdminMatchmakingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/score': typeof AdminScoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registration-assistant': typeof ApiRegistrationAssistantRoute
  '/card/$playerId': typeof CardPlayerIdRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/legal/code-of-conduct': typeof LegalCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/waiver': typeof LegalWaiverRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/t/$uid': typeof TUidRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/leaders': typeof LeadersRoute
  '/legal': typeof LegalRouteWithChildren
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/bracelet': typeof AccountBraceletRoute
  '/account/donate': typeof AccountDonateRoute
  '/account/minors': typeof AccountMinorsRoute
  '/account/payment-proof': typeof AccountPaymentProofRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/team': typeof AccountTeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/draft': typeof AdminDraftRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/league': typeof AdminLeagueRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/matchmaking': typeof AdminMatchmakingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/score': typeof AdminScoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registration-assistant': typeof ApiRegistrationAssistantRoute
  '/card/$playerId': typeof CardPlayerIdRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/legal/code-of-conduct': typeof LegalCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/waiver': typeof LegalWaiverRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/t/$uid': typeof TUidRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/leaders': typeof LeadersRoute
  '/legal': typeof LegalRouteWithChildren
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/bracelet': typeof AccountBraceletRoute
  '/account/donate': typeof AccountDonateRoute
  '/account/minors': typeof AccountMinorsRoute
  '/account/payment-proof': typeof AccountPaymentProofRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/team': typeof AccountTeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/draft': typeof AdminDraftRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/league': typeof AdminLeagueRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/matchmaking': typeof AdminMatchmakingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/score': typeof AdminScoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registration-assistant': typeof ApiRegistrationAssistantRoute
  '/card/$playerId': typeof CardPlayerIdRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/legal/code-of-conduct': typeof LegalCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/waiver': typeof LegalWaiverRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/t/$uid': typeof TUidRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/auth'
    | '/development'
    | '/faq'
    | '/gallery'
    | '/leaders'
    | '/legal'
    | '/mcp'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/sponsors'
    | '/standings'
    | '/teams'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/bracelet'
    | '/account/donate'
    | '/account/minors'
    | '/account/payment-proof'
    | '/account/profile'
    | '/account/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/donations'
    | '/admin/draft'
    | '/admin/gallery'
    | '/admin/import'
    | '/admin/league'
    | '/admin/ledger'
    | '/admin/matchmaking'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/refunds'
    | '/admin/roster'
    | '/admin/schedule'
    | '/admin/score'
    | '/admin/settings'
    | '/admin/users'
    | '/api/registration-assistant'
    | '/card/$playerId'
    | '/consent/$token'
    | '/divisions/$slug'
    | '/legal/code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund-policy'
    | '/legal/terms'
    | '/legal/waiver'
    | '/players/$playerId'
    | '/t/$uid'
    | '/account/'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/auth'
    | '/development'
    | '/faq'
    | '/gallery'
    | '/leaders'
    | '/legal'
    | '/mcp'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/sponsors'
    | '/standings'
    | '/teams'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/bracelet'
    | '/account/donate'
    | '/account/minors'
    | '/account/payment-proof'
    | '/account/profile'
    | '/account/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/donations'
    | '/admin/draft'
    | '/admin/gallery'
    | '/admin/import'
    | '/admin/league'
    | '/admin/ledger'
    | '/admin/matchmaking'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/refunds'
    | '/admin/roster'
    | '/admin/schedule'
    | '/admin/score'
    | '/admin/settings'
    | '/admin/users'
    | '/api/registration-assistant'
    | '/card/$playerId'
    | '/consent/$token'
    | '/divisions/$slug'
    | '/legal/code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund-policy'
    | '/legal/terms'
    | '/legal/waiver'
    | '/players/$playerId'
    | '/t/$uid'
    | '/account'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/auth'
    | '/development'
    | '/faq'
    | '/gallery'
    | '/leaders'
    | '/legal'
    | '/mcp'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/sponsors'
    | '/standings'
    | '/teams'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/bracelet'
    | '/account/donate'
    | '/account/minors'
    | '/account/payment-proof'
    | '/account/profile'
    | '/account/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/donations'
    | '/admin/draft'
    | '/admin/gallery'
    | '/admin/import'
    | '/admin/league'
    | '/admin/ledger'
    | '/admin/matchmaking'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/refunds'
    | '/admin/roster'
    | '/admin/schedule'
    | '/admin/score'
    | '/admin/settings'
    | '/admin/users'
    | '/api/registration-assistant'
    | '/card/$playerId'
    | '/consent/$token'
    | '/divisions/$slug'
    | '/legal/code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund-policy'
    | '/legal/terms'
    | '/legal/waiver'
    | '/players/$playerId'
    | '/t/$uid'
    | '/account/'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  DevelopmentRoute: typeof DevelopmentRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LeadersRoute: typeof LeadersRoute
  LegalRoute: typeof LegalRouteWithChildren
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AccountBraceletRoute: typeof AccountBraceletRoute
  AccountDonateRoute: typeof AccountDonateRoute
  AccountMinorsRoute: typeof AccountMinorsRoute
  AccountPaymentProofRoute: typeof AccountPaymentProofRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountTeamRoute: typeof AccountTeamRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminDraftRoute: typeof AdminDraftRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLeagueRoute: typeof AdminLeagueRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminMatchmakingRoute: typeof AdminMatchmakingRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminRosterRoute: typeof AdminRosterRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminScoreRoute: typeof AdminScoreRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiRegistrationAssistantRoute: typeof ApiRegistrationAssistantRoute
  CardPlayerIdRoute: typeof CardPlayerIdRoute
  ConsentTokenRoute: typeof ConsentTokenRoute
  DivisionsSlugRoute: typeof DivisionsSlugRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TUidRoute: typeof TUidRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bracelet': {
      id: '/account/bracelet'
      path: '/account/bracelet'
      fullPath: '/account/bracelet'
      preLoaderRoute: typeof AccountBraceletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/donate': {
      id: '/account/donate'
      path: '/account/donate'
      fullPath: '/account/donate'
      preLoaderRoute: typeof AccountDonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/minors': {
      id: '/account/minors'
      path: '/account/minors'
      fullPath: '/account/minors'
      preLoaderRoute: typeof AccountMinorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/payment-proof': {
      id: '/account/payment-proof'
      path: '/account/payment-proof'
      fullPath: '/account/payment-proof'
      preLoaderRoute: typeof AccountPaymentProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/team': {
      id: '/account/team'
      path: '/account/team'
      fullPath: '/account/team'
      preLoaderRoute: typeof AccountTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/admin/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/draft': {
      id: '/admin/draft'
      path: '/admin/draft'
      fullPath: '/admin/draft'
      preLoaderRoute: typeof AdminDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/league': {
      id: '/admin/league'
      path: '/admin/league'
      fullPath: '/admin/league'
      preLoaderRoute: typeof AdminLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/admin/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/matchmaking': {
      id: '/admin/matchmaking'
      path: '/admin/matchmaking'
      fullPath: '/admin/matchmaking'
      preLoaderRoute: typeof AdminMatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/admin/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roster': {
      id: '/admin/roster'
      path: '/admin/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AdminRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/score': {
      id: '/admin/score'
      path: '/admin/score'
      fullPath: '/admin/score'
      preLoaderRoute: typeof AdminScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registration-assistant': {
      id: '/api/registration-assistant'
      path: '/api/registration-assistant'
      fullPath: '/api/registration-assistant'
      preLoaderRoute: typeof ApiRegistrationAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$playerId': {
      id: '/card/$playerId'
      path: '/card/$playerId'
      fullPath: '/card/$playerId'
      preLoaderRoute: typeof CardPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$token': {
      id: '/consent/$token'
      path: '/consent/$token'
      fullPath: '/consent/$token'
      preLoaderRoute: typeof ConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/$slug': {
      id: '/divisions/$slug'
      path: '/divisions/$slug'
      fullPath: '/divisions/$slug'
      preLoaderRoute: typeof DivisionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/code-of-conduct': {
      id: '/legal/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/legal/code-of-conduct'
      preLoaderRoute: typeof LegalCodeOfConductRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refund-policy': {
      id: '/legal/refund-policy'
      path: '/refund-policy'
      fullPath: '/legal/refund-policy'
      preLoaderRoute: typeof LegalRefundPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/waiver': {
      id: '/legal/waiver'
      path: '/waiver'
      fullPath: '/legal/waiver'
      preLoaderRoute: typeof LegalWaiverRouteImport
      parentRoute: typeof LegalRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$uid': {
      id: '/t/$uid'
      path: '/t/$uid'
      fullPath: '/t/$uid'
      preLoaderRoute: typeof TUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalCodeOfConductRoute: typeof LegalCodeOfConductRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundPolicyRoute: typeof LegalRefundPolicyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalWaiverRoute: typeof LegalWaiverRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCodeOfConductRoute: LegalCodeOfConductRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundPolicyRoute: LegalRefundPolicyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalWaiverRoute: LegalWaiverRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  DevelopmentRoute: DevelopmentRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LeadersRoute: LeadersRoute,
  LegalRoute: LegalRouteWithChildren,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AccountBraceletRoute: AccountBraceletRoute,
  AccountDonateRoute: AccountDonateRoute,
  AccountMinorsRoute: AccountMinorsRoute,
  AccountPaymentProofRoute: AccountPaymentProofRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountTeamRoute: AccountTeamRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminDraftRoute: AdminDraftRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLeagueRoute: AdminLeagueRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminMatchmakingRoute: AdminMatchmakingRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminRosterRoute: AdminRosterRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminScoreRoute: AdminScoreRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiRegistrationAssistantRoute: ApiRegistrationAssistantRoute,
  CardPlayerIdRoute: CardPlayerIdRoute,
  ConsentTokenRoute: ConsentTokenRoute,
  DivisionsSlugRoute: DivisionsSlugRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TUidRoute: TUidRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
